// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zbifenuizimkqugjgyom.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpiaWZlbnVpemlta3F1Z2pneW9tIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ5MTQxODcsImV4cCI6MjA2MDQ5MDE4N30.uo3SVuWfaGxdw01r9kcYDyLqkC-MQ8_2d_nNqeLczho";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);